name: Deploy MkDocs site

on:
  push:
    branches: [ main ]
    paths:
      - "mkdocs.yml"
      - "docs/**"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install -U pip mkdocs
          mkdocs --version
      - name: Deploy to gh-pages
        run: mkdocs gh-deploy --force --remote-branch gh-pages

