name: Build & Release Wheels (CUDA manylinux)

on:
  push:
    branches: [ main ]
    paths:
      - "pyproject.toml"
      - "src/**"
      - "CMakeLists.txt"
      - "cmake/**"
      - ".github/workflows/wheels.yml"

  workflow_dispatch: {}
  push:
    tags: ["v*"]

permissions:
  contents: write

env:
  PACKAGE_NAME: gasal2_py
  # Build these CPython versions (linux x86_64)
  PYTHON_BUILD_PATS: "cp39-* cp310-* cp311-* cp312-*"

jobs:
  build-linux:
    name: Build manylinux wheels (CUDA)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ml_image:
          - kind: manylinux2014
            tag: "gasal2-manylinux2014-cuda:12.4.0"
            base: "quay.io/pypa/manylinux2014_x86_64"
            cuda_from: "nvidia/cuda:12.4.0-devel-centos7"
            env_var: "CIBW_MANYLINUX_X86_64_IMAGE"
          - kind: manylinux_2_28
            tag: "gasal2-manylinux_2_28-cuda:12.4.1"
            base: "quay.io/pypa/manylinux_2_28_x86_64"
            cuda_from: "nvidia/cuda:12.4.1-devel-rockylinux8"
            env_var: "CIBW_MANYLINUX_2_28_X86_64_IMAGE"
    steps:
      - uses: actions/checkout@v4
        with:
          # For setuptools-scm during tag builds, fetch full history and tags.
          fetch-depth: 0
          submodules: false   # external deps handled by your CMake ExternalProject

      - name: Set up Python for helper tooling
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build custom CUDA-enabled manylinux image (${{ matrix.ml_image.kind }})
        shell: bash
        run: |
          cat > Dockerfile.ci <<'DOCKER'
          ARG BASE
          ARG CUDA_FROM
          FROM ${CUDA_FROM} as cuda
          # provides /usr/local/cuda

          FROM ${BASE}
          # minimal tools; package manager differs per base
          RUN yum -y install git && yum clean all || true \
           || (microdnf -y install git && microdnf clean all || true) \
           || (dnf -y install git && dnf clean all || true)
          # copy CUDA to neutral prefix
          COPY --from=cuda /usr/local/cuda /opt/cuda
          ENV PATH="/opt/cuda/bin:${PATH}" CUDA_HOME="/opt/cuda"
          DOCKER
          docker build \
            --build-arg BASE=${{ matrix.ml_image.base }} \
            --build-arg CUDA_FROM=${{ matrix.ml_image.cuda_from }} \
            -t ${{ matrix.ml_image.tag }} \
            -f Dockerfile.ci .

      - name: Install cibuildwheel & build tools
        run: |
          python -m pip install -U pip
          python -m pip install "cibuildwheel>=2.20" build

      - name: Select image override env var for cibuildwheel
        run: |
          echo "${{ matrix.ml_image.env_var }}=${{ matrix.ml_image.tag }}" >> "$GITHUB_ENV"

      - name: Build wheels with cibuildwheel on ${{ matrix.ml_image.kind }} (continue on error)
        env:
          # Limit to x86_64 on Linux
          CIBW_ARCHS_LINUX: x86_64
          # Build the selected CPython versions
          CIBW_BUILD: ${{ env.PYTHON_BUILD_PATS }}
          # Skip PyPy and musllinux in this CUDA workflow
          CIBW_SKIP: "pp* *-musllinux_*"
          # Ensure build deps are available inside the PEP 517 env
          CIBW_BEFORE_BUILD: >
            git submodule update --init --recursive || true &&
            python -m pip install -U pip cmake>=3.27 ninja>=1.11 scikit-build-core>=0.10 pybind11>=2.12
          # CUDA discovery + lib paths + nvcc path + arches
          CIBW_ENVIRONMENT: >
            CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release
                        -DSKBUILD_BUILD_VERBOSE=1
                        -DCMAKE_VERBOSE_MAKEFILE=ON
                        -DCMAKE_CUDA_COMPILER=/opt/cuda/bin/nvcc
                        -DCMAKE_CUDA_ARCHITECTURES=70;75;80;86
                        -DGASAL2_CUDA_HOME=/opt/cuda
                        -DCUDAToolkit_ROOT=/opt/cuda
                        -DCUDA_TOOLKIT_ROOT_DIR=/opt/cuda"
            PATH=/opt/cuda/bin:$PATH
            NVCC=/opt/cuda/bin/nvcc
            CUDA_HOME=/opt/cuda
            CUDA_PATH=/opt/cuda
            CMAKE_PREFIX_PATH=/opt/cuda
            LD_LIBRARY_PATH=/opt/cuda/lib64:/opt/cuda/targets/x86_64-linux/lib:$LD_LIBRARY_PATH
            SKBUILD_CMAKE_BUILD_PARALLEL_LEVEL=2
          # Be verbose so failures provide CMake diagnostics
          CIBW_BUILD_VERBOSITY: "3"
          # Ensure auditwheel sees libcudart in the repair phase
          CIBW_REPAIR_WHEEL_COMMAND: >
            bash -lc 'export LD_LIBRARY_PATH=/opt/cuda/lib64:/opt/cuda/targets/x86_64-linux/lib:$LD_LIBRARY_PATH;
                      auditwheel -v repair {wheel} -w {dest_dir} --exclude libcuda.so.1'
          # Disable tests in CUDA builds by default; customize if you add GPU-capable tests
          CIBW_TEST_SKIP: "*"
        run: |
          # Don't fail the step if some wheels fail; upload whatever was built
          python -m cibuildwheel --output-dir wheelhouse || true

      - name: Build sdist
        # sdist is independent; keep it even if some wheels failed
        run: |
          python -m build --sdist --outdir dist

      - name: Upload artifacts (whatever succeeded)
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.ml_image.kind }}
          path: |
            wheelhouse/*.whl
            dist/*.tar.gz
          if-no-files-found: ignore

  release:
    name: Create GitHub Release (tag builds only)
    runs-on: ubuntu-latest
    needs: build-linux
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: ./artifacts

      - name: Flatten artifacts for release/publish
        run: |
          mkdir -p to-release
          find artifacts -type f \( -name "*.whl" -o -name "*.tar.gz" \) -exec cp {} to-release/ \; || true
          ls -l to-release || true

      - name: Ensure we have at least one file
        run: |
          if ! ls to-release/* >/dev/null 2>&1; then
            echo "No distributions built; skipping release"; exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: GASAL2-Py ${{ github.ref_name }}
          body: |
            CUDA-enabled manylinux wheels (2014 & 2_28).
            Built from commit ${{ github.sha }}.
          files: to-release/*

  publish-pypi:
    name: Publish to PyPI (tag builds only)
    runs-on: ubuntu-latest
    needs: release
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: ./artifacts

      - name: Collect distributions
        run: |
          mkdir -p to-publish
          find artifacts -type f \( -name "*.whl" -o -name "*.tar.gz" \) -exec cp {} to-publish/ \; || true
          if ! ls to-publish/* >/dev/null 2>&1; then
            echo "No dists to publish; exiting gracefully"; exit 0
          fi

      # Option A: API token-based publish (keep this if you already use a token)
      - name: Publish (if token present)
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        if: ${{ env.PYPI_API_TOKEN != '' }}
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          password: ${{ env.PYPI_API_TOKEN }}
          packages_dir: to-publish
          skip_existing: true
